### ISSUE TITLE
model训练过程求助

### ISSUE THREAD

**Issue by Barnail** [dxbjtu1228/TCMPR#1]
您好 请问可以分享一下model文件的训练过程吗 谢谢

**Comment by xdong97** [comment]
感谢提问和对本项目的关注！模型的训练过程见代码的“training_and_testing”函数，此函数实现了以 经过症状术语映射+网络嵌入特征融合 后形成的症状特征作为输入，经一层卷积+三层MLP+softmax训练（训练轮数、batchsize、dimension等参数均可调）后能够对候选药物进行评分，从而实现药物推荐过程。
